### PR TITLE
Feat/faucet subscription

### PR DESCRIPTION
**Pull request by amimart**
In response to GraphQL API changes on the https://github.com/okp4/cosmos-faucet/pull/79 backend implementation, the client side is adjusted here.

The `send` mutation will no longer return underlying transaction informations, I therefore propose to wire with the `send` subscription instead.

A little fix has been made in the error handling, by fetching the transaction code we are able to know if the transaction was accepted or not in the blockchain's mempool.

Additionally, as fund requests can now take a non negligible amount of time I took the opportunity to introduce a progress bar. A progress bar on which CSS scientists are very welcome to help if relevant (and I think it is 😉).

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
Great! 😊

**Review by JoeyDjr — APPROVED** [review]
Maybe later we can change the progress bar by a simple loader (a Loader component), it will be better.

**Comment by fredericvilcot** [comment]
Thanks @amimart for these changes 🙏
If you don't mind, I will push some commits to replace the `ProgressBar` by a tiny loader directly in the submit button(s) to better fit the UI.

**Comment by amimart** [comment]
> Thanks @amimart for these changes 🙏 If you don't mind, I will push some commits to replace the `ProgressBar` by a tiny loader directly in the submit button(s) to better fit the UI.

Yes please, make it sexy 🙏

**Comment by fredericvilcot** [comment]
@ccamel @amimart 
Ok guys, I  pushed some commits to add a small spinner instead of buttons when transaction is loading + some refactor.
Sounds good to me, everything works smoothly 😌
Thanks @amimart for your great contribution 🚀
Let's merge it if OK for you!

**Review by fredericvilcot — APPROVED** [review]

**Pull request merged**
