### PR TITLE
ci: checkout out repository before checking new dependencies

### PR DESCRIPTION
**Pull request by nperon**
This PR fixes the report new dependencies step in the ci workflows.

As a result an output like the following is to be expected in the PR page:

hiwelo_action
This is when a new item called 'smallest' version 1.0.1 is added to the package.json dependencies section.

**Note**
We additionaly experimented another action labelled lirantal/github-action-new-dependencies-advisor@v1.1.1 
The latter adds metrics on the reliability and quality of each new dependency:
lirantal_action
The [liranthal github action](https://github.com/lirantal/github-action-new-dependencies-advisor) appears to be under the MIT license although it advertises a commercial logo. 

I am interested in feedback on whether we should choose liranthal or stick to hiwelo/new-dependencies-action.

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
Okay! Great. +1:

I don't have a strong opinion on whether to adopt another GitHub action or not. The choice has to be made with a bit of hindsight.

**Review by fredericvilcot — APPROVED** [review]

**Review by amimart — CHANGES_REQUESTED** [review]
Good catch, you didn't touch it but my only remark is about the token used to post the comment, could you please use the `secrets.OKP4_TOKEN` instead?

**Comment by nperon** [comment]
The right token is used now. Thanks @amimart.

**Comment by nperon** [comment]
I will keep on with the hiwelo action. Snyk metrics can always be requested for free at [this link](https://snyk.io/advisor/) for whatever new npm dependency.

**Pull request merged**
