### PR TITLE
Feat/upload files

### PR DESCRIPTION
**Pull request by fredericvilcot**
👉 This PR adds a new feature: upload files on a S3 (protocol) server like Minio.

🧠 This new feature is implemented under hexagonal architecture and event sourcing principles: the main idea beeing to create a "contract" between hexagone (core) and outside (a FilePort) that will be implemented by any gateway (the outside).

✅ What have been added (not limited list 😌)?

- the `File` port (interfaces which must be implemented by adapters)
- a `FileRegistryGateway` that allows to register any kind of gateway that implements the port via a strategy pattern
- a `S3FileGateway` that allows to upload a file and track its progression on any S3 based server
- a `UploadFiles` command (use-case) that will orchestrate the whole asynchronous process thanks to an `execute` function that guarantees that all operations are executed in the **same session** (e.g if a gateway needs a websocket connection, that guarantees that the connection / upload / ... / closing are executed in the same session)
- a complete error management that can catch any error in the upload process, from invoking the command to executing the upload operation on server
- a complete task tracking that offers, for each file to upload, the capability to track the whole asynchronous progress (e.g track the bytes sent / stream)
- some modifications in the file store to accept `dependencies` in the `ThunkMiddleware`
- some new store selectors to compute file sizes or to access an array of current tasks 
- some minor refactoring to handle the changes

🧪The whole behavior in under unit-testing (`UploadFiles` as SUT)

⚠️ There is no test suite for the `task` primary adapters because I had to hack the way command are invoked by creating fake events that are not Event Sourcing based... THIS WILL BE REPLACED WITH THE COMMAND BUS 😎

❤️ The port is protocol agnostic, so it will be easy to add an `IPFS` gateway in a very soon future!

### CODE REVIEW

**Review by JoeyDjr — APPROVED** [review]
:exploding_head: 
lgtm, great job

**Review by lolottetheclash — APPROVED** [review]
Great Job with great description 👍👍👍 Well done!

**Review by ErikssonJoakim — APPROVED** [review]
LGTM 😄

**Review by RaphaelEscrig — APPROVED** [review]
Really nice ! 🚀

**Comment by fredericvilcot** [comment]
@ccamel 
I think we could merge this one and improve later how to reference a dataset in the database.
This mainly to prevent from PR never closed...
What do you think?

**Review by ccamel — APPROVED** [review]

**Pull request merged**
