### PR TITLE
Docs/refactor story theme switches

### PR DESCRIPTION
**Pull request by ErikssonJoakim**
This PR is part of #459.

It puts the theme switch out of every story where it's not part of the component.

**Current overview story:**
Capture d’écran 2022-09-02 à 08 48 44

**Overview story in PR:**
Capture d’écran 2022-09-02 à 08 48 34

**Current property story:**
Capture d’écran 2022-09-02 à 08 51 46

**Property story in PR:**
Capture d’écran 2022-09-02 à 08 51 20

### CODE REVIEW

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
Could you please update the PR's description by adding some screenshots of a random component (ex: `Button`) before and after your changes?
By the way, I think it will be better (as we discussed together a couple of days ago) to systematically import the `component.scss` file in each story to prevent from losing style if the only story that imports the file is deleted.
Thanks 😊

**Comment by ErikssonJoakim** [comment]
@fredericvilcot Good idea. 
Regarding the import: I plan to implement it in each individual component story refactor. This PR is a part from those just because the changes affect almost every component story.

**Review by fredericvilcot — APPROVED** [review]
All good!

**Review by lolottetheclash — APPROVED** [review]
Nice improvement !

**Review by JoeyDjr — APPROVED** [review]

**Review by ccamel — APPROVED** [review]

**Pull request merged**
