### PR TITLE
Feat/stepper component

### PR DESCRIPTION
**Pull request by JoeyDjr**
This PR concerns the implementation of the stepper component
image
👉 linked issue: https://github.com/okp4/ui/issues/391

### CODE REVIEW

**Comment by JoeyDjr** [comment]
The PR is now ready for review.

**Review by fredericvilcot — APPROVED** [review]
That's a real good job, well done 👏

**Review by lolottetheclash — APPROVED** [review]
Very good job, well done 👍

**Review by ErikssonJoakim — APPROVED** [review]
Nice component 😎 I approve 😃 👍

**Review by ccamel — APPROVED** [review]
LGTM. Thanks for the great component. 👍

**Pull request merged**
