### PR TITLE
ci: fix PR comment publish

### PR DESCRIPTION
**Pull request by ad2ien**
Fix publish action by commenting a pull request:
A git flow or an issue trigger don't end up with the same context. In case of a comment there's a query to do to get the branch of the pull request.

The project is forked so that it's possible to dev on main branch and test the action.

Test with fix/ci-publish branch pull request:
https://github.com/ad2ien/ui/actions/runs/2504934920
Tries to push `ghcr.io/ad2ien/ui:fix-ci-publish` docker image and tries for npm package:
```
🚀 Publishing npm package with following command line: yarn publish --no-git-tag-version --non-interactive --prerelease --preid fix-ci-publish.20220615202551 --tag fix-ci-publish
```

### CODE REVIEW

**Comment by ad2ien** [comment]
Some failing test due to missing tokens are not relevant, I don't know if it's possible to bypass...

**Review by amimart — DISMISSED** [review]
Thanks for figuring this out!

Indeed, there is some fail on actions running on PR from forked head ref, we can address them in a second time.

**Review by ccamel — DISMISSED** [review]
LGTM! Thanks 👍

**Review by fredericvilcot — DISMISSED** [review]

**Review by lolottetheclash — APPROVED** [review]
nice work !!!

**Comment by amimart** [comment]
@ad2ien Can you please rebase your branch ? We'll see if https://github.com/okp4/ui/pull/282 make it green 💚.

**Review by amimart — APPROVED** [review]
Excellent, it worked 😉

**Pull request merged**
