### PR TITLE
ci: add pr publish workflow

### PR DESCRIPTION
**Pull request by ad2ien**
This PR to be able to publish a branch on demand by commenting a PR with `/publish` message. https://github.com/okp4/product/issues/590

### CODE REVIEW

**Review by ccamel — APPROVED** [review]

**Review by fredericvilcot — APPROVED** [review]
Great!

**Review by lolottetheclash — APPROVED** [review]
Nice !!!👍

**Review by amimart — APPROVED** [review]
Great 👍

**Comment by ccamel** [comment]
@ad2ien Ready to merge? ☺️

**Pull request merged**
