### PR TITLE
Feat/Faucet organism

### PR DESCRIPTION
**Pull request by fredericvilcot**
This PR implement https://github.com/okp4/ui/issues/125
This is the whole `Faucet` view in one single component that is able to fire all user use cases by itself with full autonomy.

Nota: The story will come in a next dedicated PR

### CODE REVIEW

**Review by amimart — APPROVED** [review]
Seems good to me, as far as I can tell

**Review by ccamel — APPROVED** [review]
A huge one. Thanks! 👍

**Review by JoeyDjr — APPROVED** [review]

**Review by lolottetheclash — APPROVED** [review]
What a great work, well done 💪💪💪 !!!

**Pull request merged**
